version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tenancy
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
  localstack:
    image: localstack/localstack:2.3
    environment:
      SERVICES: s3
    ports:
      - '4566:4566'
    volumes:
      - './.localstack:/var/lib/localstack'
